// export const baseUrl = 'http://54.88.46.234:4000/api/'; Live Url
export const baseUrl = 'http://192.168.29.104:4005/api/'; // Local Url
export const loginEndPointURL = 'auth/login';
export const forgotPasswordEndPointURL = "auth/forgot-password";
export const getProfileDataEndPointURL = "auth/profile";
export const updateProfileEndPointURl = "auth/profile";
export const sideBarValuesEndPointURL = "admin/sidebar";
export const getLessonByIdEndpointURL = "lessons/module-id/";
export const deleteLessonById = "admin/lessons/";
export const addQuizInLessonEndPointURL = "admin/quizzes";
export const getAllQuizByLessonIdEndPointURL = "quizzes/lesson-id/";
export const updateQuizByLessonIdEndPointURL = "admin/quizzes/";
export const updateUserProfileDataEndPointURL = "auth/profile";
export const changePasswordEndPointURL = "auth/change-password";
export const getLessaonByIdEndPointURL = "lessons/";
export const updateLessonEndPointURL = "admin/lessons/";
export const getAllUserDataEndPointURL = "admin/get-user-list";
export const otpVerifyEndPointURL = "auth/verify-forgot-password";
export const newPasswordEndPointURL = "auth/change-password-by-email";
export const deleteUserDataEndPointURL = "admin/delete-user-by-id/";